src/main/java/com/pizzeria/domain/Order.java
package com.pizzeria.domain;

import java.util.Collection;
import java.util.Date;

public class Order {
    final private Number id;
    final private User user;
    final private Number userId;
    final private Collection<SelectedPizza> selectedPizzas;
    final private Date deliveryDate;
    final private Boolean modifiable;
    final private Boolean complete;

    public static class Builder {
        private Number id;
        private User user;
        private Collection<SelectedPizza> selectedPizzas;
        private Date deliveryDate;
        private Boolean modifiable = true;
        private Boolean complete = false;

        public Builder setId(Number id) {
            this.id = id;
            return this;
        }

        public Builder setUser(User user) {
            this.user = user;
            return this;
        }

        public Builder setSelectedPizzas(Collection<SelectedPizza> selectedPizza) {
            this.selectedPizzas = selectedPizza;
            return this;
        }

        public Builder setDeliveryDate(Date deliveryDate) {
            this.deliveryDate = deliveryDate;
            return this;
        }

        public Builder setFromOrder(Order order) {
            if (order != null) {
                setId(order.id);
                setUser(order.user);
                setSelectedPizzas(order.selectedPizzas);
                setDeliveryDate(order.deliveryDate);
                setComplete(order.complete);
                setModifiable(order.modifiable);
            }
            return this;
        }

        public Builder setModifiable(Boolean modifiable) {
            this.modifiable = modifiable;
            return this;
        }

        public Builder setComplete(Boolean complete) {
            this.complete = complete;
            return this;
        }

        public Number getId() {
            return id;
        }

        public User getUser() {
            return user;
        }

        public Collection<SelectedPizza> getSelectedPizzas() {
            return selectedPizzas;
        }

        public Date getDeliveryDate() {
            return deliveryDate;
        }

        public Boolean getModifiable() {
            return modifiable;
        }

        public Boolean getComplete() {
            return complete;
        }

        public Order build() {
            Number userId = null;
            if (user != null) {
                userId = user.getId();
            }
            return new Order(id, user, userId, selectedPizzas, deliveryDate, modifiable, complete);
        }

    }

    public static Builder builder() {
        return new Builder();
    }

    public Builder getBuilder() {
        return Order.builder().setFromOrder(this);
    }

    private Order(Number id, User user, Number userId,
                  Collection<SelectedPizza> pizzas, Date deliveryDate, Boolean modifiable, Boolean complete) {
        this.id = id;
        this.user = user;
        this.userId = userId;
        this.selectedPizzas = pizzas;
        this.deliveryDate = deliveryDate;
        this.modifiable = modifiable;
        this.complete = complete;
    }

    public Number getId() {
        return id;
    }

    public User getUser() {
        return user;
    }

    public Number getUserId() {
        return userId;
    }

    public Collection<SelectedPizza> getSelectedPizzas() {
        return selectedPizzas;
    }

    public Date getDeliveryDate() {
        return deliveryDate;
    }

    public Float getTotalPrice() {
        float total = 0;
        for (SelectedPizza selectedPizza : selectedPizzas) {
            total += selectedPizza.getTotalPrice();
        }
        return total;
    }

    public Integer getTotalQuantity() {
        int total = 0;
        for (SelectedPizza selectedPizza : selectedPizzas) {
            total += selectedPizza.getQuantity().intValue();
        }
        return total;
    }

    public Boolean getModifiable() {
        return modifiable;
    }

    public Boolean getComplete() {
        return complete;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Order)) return false;

        Order order = (Order) o;

        if (deliveryDate != null ? !deliveryDate.equals(order.deliveryDate) : order.deliveryDate != null) return false;
        if (id != null ? !id.equals(order.id) : order.id != null) return false;
        if (selectedPizzas != null ? !selectedPizzas.equals(order.selectedPizzas) : order.selectedPizzas != null)
            return false;
        if (user != null ? !user.equals(order.user) : order.user != null) return false;
        if (userId != null ? !userId.equals(order.userId) : order.userId != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + user.hashCode();
        result = 31 * result + (selectedPizzas != null ? selectedPizzas.hashCode() : 0);
        result = 31 * result + deliveryDate.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "Order{" +
                "deliveryDate='" + deliveryDate + '\'' +
                ", user=" + user +
                ", id=" + id +
                '}';
    }
}

src/main/java/com/pizzeria/controller/HomeController.java
package com.pizzeria.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
@RequestMapping("/")
public class HomeController {

    @RequestMapping(method = RequestMethod.GET)
    public String printWelcome() {
        return "home";
    }
}

src/main/java/com/pizzeria/controller/OrderController.java
package com.pizzeria.controller;

import com.pizzeria.authentication.Authentication;
import com.pizzeria.controller.form.OrderFormBean;
import com.pizzeria.domain.Order;
import com.pizzeria.domain.User;
import com.pizzeria.services.OrderService;
import com.pizzeria.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.support.SessionStatus;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import java.util.Collection;
import java.util.Map;

@Controller
@RequestMapping("/order")
public class OrderController {
    @Autowired
    UserService userService;
    @Autowired
    OrderService orderService;
    @Autowired
    Authentication authentication;

    @RequestMapping(value = "new", method = RequestMethod.GET)
    public String newOrder(ModelMap model,
                           HttpSession session,
                           RedirectAttributes redirectAttrs) {
        Map tempOrder = (Map) session.getAttribute("tempOrder");
        OrderFormBean orderFormBean = new OrderFormBean();
        if (tempOrder == null) {
            redirectAttrs.addFlashAttribute("messageError", "You should put some pizza to checkout");
            return "redirect:/";
        }
        if (tempOrder.containsKey("id")) {
            Order order = orderService.getOrder(tempOrder.get("id").toString());
            orderFormBean.setCompleteDate(order.getDeliveryDate());
        }
        model.addAttribute("orderForm", orderFormBean);
        model.addAttribute("tempOrder", tempOrder);
        return "orderForm";
    }

    @RequestMapping(value = "create", method = RequestMethod.POST)
    public String createOrder(@Valid @ModelAttribute("orderForm") OrderFormBean orderForm,
                              BindingResult result,
                              SessionStatus sessionStatus,
                              HttpSession session,
                              RedirectAttributes redirectAttrs) {
        orderForm.validate(result);
        if (result.hasErrors()) {
            return "orderForm";
        }

        if (!authentication.isLogged()) {
            redirectAttrs.addFlashAttribute("messageError", "You are must be logged to complete the order");
            return authentication.getRedirectToLogin();
        }
        User user = authentication.getUserFromSession();

        Map tempOrder = (Map) session.getAttribute("tempOrder");
        Order newOrder = Order.builder()
                .setDeliveryDate(orderForm.getCompleteDate())
                .setUser(user).build();
        try {

            newOrder = orderService.insertOrUpdateOrderByTempOrderMap(newOrder, tempOrder, user);

        } catch (Exception e) {
            redirectAttrs.addFlashAttribute("messageError", e.getMessage());
            e.printStackTrace();
            return "redirect:/order/show";
        }
        session.setAttribute("tempOrder", null);
        session.removeAttribute("tempOrder");
        sessionStatus.setComplete();

        redirectAttrs.addFlashAttribute("messageSuccess", "The order "
                + newOrder.getId()
                + " created with success ");

        return "redirect:/order/show";
    }

    @RequestMapping(value = "show", method = RequestMethod.GET)
    public String showOwnOrder(ModelMap model, HttpSession session) {
        User user = (User) session.getAttribute("user");
        if (user == null) {
            return "redirect:/login";
        }

        Collection<Order> orders = orderService.getOrderListByUser(user);

        model.addAttribute("orders", orders);
        return "ordersShow";
    }

    @RequestMapping(value = "{id}/delete", method = RequestMethod.POST)
    public String destroyOrder(@PathVariable("id") String orderIdString,
                               RedirectAttributes redirectAttrs) {
        if (!authentication.isLogged()) {
            redirectAttrs.addFlashAttribute("messageError", "You are must be logged to delete the order");
            return authentication.getRedirectToLogin();
        }
        try {

            orderService.deleteData(orderIdString, authentication.getUserFromSession());

            redirectAttrs.addFlashAttribute("messageSuccess", "The order "
                    + orderIdString
                    + " deleted with success ");
        } catch (Exception ex) {
            redirectAttrs.addFlashAttribute("messageError", ex.getMessage());

        }
        return "redirect:/order/show";
    }

    @RequestMapping(value = "{id}/complete", method = RequestMethod.GET)
    public String completeOrder(@PathVariable("id") String orderIdString,
                                RedirectAttributes redirectAttrs) {
        if (!authentication.isLogged()) {
            redirectAttrs.addFlashAttribute("messageError", "You are must be logged to declare complete the order");
            return authentication.getRedirectToLogin();
        }
        try {

            orderService.setComplete(orderIdString, authentication.getUserFromSession());

            redirectAttrs.addFlashAttribute("messageSuccess", "The order "
                    + orderIdString
                    + " declared completed with success ");
        } catch (Exception ex) {
            redirectAttrs.addFlashAttribute("messageError", ex.getMessage());
        }
        return "redirect:/order/show";
    }

    @RequestMapping(value = "{id}/uncompleted", method = RequestMethod.GET)
    public String uncompletedOrder(@PathVariable("id") String orderIdString,
                                   RedirectAttributes redirectAttrs) {
        if (!authentication.isLogged()) {
            redirectAttrs.addFlashAttribute("messageError", "You are must be logged to declare uncompleted the order");
            return authentication.getRedirectToLogin();
        }
        try {

            orderService.setUncompleted(orderIdString, authentication.getUserFromSession());

            redirectAttrs.addFlashAttribute("messageSuccess", "The order "
                    + orderIdString
                    + " declared uncompleted with success ");
        } catch (Exception ex) {
            redirectAttrs.addFlashAttribute("messageError", ex.getMessage());
        }
        return "redirect:/order/show";
    }

    @RequestMapping(value = "{id}/unchangeable", method = RequestMethod.GET)
    public String unchangeableOrder(@PathVariable("id") String orderIdString,
                                    RedirectAttributes redirectAttrs) {
        if (!authentication.isLogged()) {
            redirectAttrs.addFlashAttribute("messageError", "You are must be logged to declare unchangeable the order");
            return authentication.getRedirectToLogin();
        }
        try {

            orderService.setUnchangeable(orderIdString, authentication.getUserFromSession());

            redirectAttrs.addFlashAttribute("messageSuccess", "The order "
                    + orderIdString
                    + " declared unchangeable with success ");
        } catch (Exception ex) {
            redirectAttrs.addFlashAttribute("messageError", ex.getMessage());
        }
        return "redirect:/order/show";
    }

    @RequestMapping(value = "{id}/changeable", method = RequestMethod.GET)
    public String changeableOrder(@PathVariable("id") String orderIdString,
                                  RedirectAttributes redirectAttrs) {
        if (!authentication.isLogged()) {
            redirectAttrs.addFlashAttribute("messageError", "You are must be logged to declare unchangeable the order");
            return authentication.getRedirectToLogin();
        }
        try {

            orderService.setChangeable(orderIdString, authentication.getUserFromSession());

            redirectAttrs.addFlashAttribute("messageSuccess", "The order "
                    + orderIdString
                    + " declared changeable with success ");
        } catch (Exception ex) {
            redirectAttrs.addFlashAttribute("messageError", ex.getMessage());
        }

        return "redirect:/order/show";
    }

    @RequestMapping(value = "{id}/modify", method = RequestMethod.GET)
    public String modifyOrder(@PathVariable("id") String orderIdString,
                              SessionStatus sessionStatus,
                              HttpSession session,
                              RedirectAttributes redirectAttrs) {
        if (!authentication.isLogged()) {
            redirectAttrs.addFlashAttribute("messageError", "You are must be logged to declare complete the order");
            return authentication.getRedirectToLogin();
        }

        Map orderMap = orderService.getOrderMap(orderIdString);

        session.setAttribute("tempOrder", orderMap);
        sessionStatus.setComplete();
        return "redirect:/";
    }
}

src/main/webapp/WEB-INF/views/home.jsp
<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>


<t:main-layout>
    <jsp:attribute name="javascript">
          <script src="<c:url value="/resources/js/app/orderApp.js" />"></script>
    </jsp:attribute>
    <jsp:body>
        <div class="jumbotron">
            <div class="main-pizza-img-div">
                <img async class="img-responsive"
                     src="https://dl.dropboxusercontent.com/u/14672643/Supreme_pizza_small.jpg">
            </div>

            <p><a class="btn btn-primary btn-lg go-to-pizza-table" role="button">Let's order some pizzas</a></p>
        </div>
        <t:pizzaOrderList/>
    </jsp:body>
</t:main-layout>

src/main/webapp/WEB-INF/views/orderForm.jsp
<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>


<t:main-layout>
    <form:form id="form" action="${pageContext.request.contextPath}/order/create" method="post"
               modelAttribute="orderForm" class="form-horizontal" role="form">
        <legend>Complete the order</legend>
        <div class="form-group ">
            <form:label class="col-sm-2 control-label" path="date">
                Date
            </form:label>
            <div class="col-sm-10">
                <form:input path="date" type="text" class="form-control"
                            placeholder="Choose a date in this format dd/MM/yyyy ex. 20/10/2013"
                            required="required"/>
                <s:bind path="date">
                    <c:if test="${status.error}">
                        <div class="alert alert-danger">
                            <form:errors path="date"/>
                        </div>
                    </c:if>
                </s:bind>
            </div>
        </div>
        <div class="form-group ">
            <form:label class="col-sm-2 control-label" path="time">
                Time
            </form:label>
            <div class="col-sm-10">
                <form:input path="time" type="text" class="form-control"
                            placeholder="Choose a time in this format hh:mm ex. 13:45"
                            required="required"/>
                <s:bind path="time">
                    <c:if test="${status.error}">
                        <div class="alert alert-danger">
                            <form:errors path="time"/>
                        </div>
                    </c:if>
                </s:bind>
            </div>
        </div>
        <div class="form-group ">
            <label class="col-sm-2 control-label">
                Pizzas
            </label>

            <div class="col-sm-10">
                <div class="list-group">
                    <c:forEach var="pizza" items="${tempOrder.selectedPizzas}">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading"><c:out value="${pizza.name}"/></h4>

                            <div class="list-group-item-text">
                                <p><c:out value="${pizza.ingredients}"/></p>

                                <p class="text-right">
                                    <span class="block">Quantità <c:out value="${pizza.quantity}"/></span>
                                    <span class="block">Prezzo totale
                                        <fmt:formatNumber type="number" minFractionDigits="2" maxFractionDigits="2"
                                                          value="${pizza.total_price}"/>&#8364;</span>
                                </p>
                            </div>
                        </div>
                    </c:forEach>
                </div>
            </div>
        </div>
        <div class="form-group ">
            <label class="col-sm-2 control-label">
                Total Price
            </label>

            <div class="col-sm-10">
                <p class="form-control-static">
                    <fmt:formatNumber type="number" minFractionDigits="2" maxFractionDigits="2"
                                      value="${tempOrder.total_price}"/>&#8364;
                </p>
            </div>
            <label class="col-sm-2 control-label">
                Total quantity
            </label>

            <div class="col-sm-10">
                <p class="form-control-static">
                    <c:out value="${tempOrder.total_quantity}"/></p>
            </div>
        </div>
        <p>
            <button type="submit" class="btn btn-primary">Checkout</button>
            <a href="${pageContext.request.contextPath}/" class="btn">Modify Order</a>
        </p>
    </form:form>

</t:main-layout>

src/main/webapp/WEB-INF/views/ordersShow.jsp
<%--@elvariable id="user" type="com.pizzeria.domain.User"--%>
<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>


<t:main-layout>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th>Id</th>
            <th>Delivery Date Time</th>
            <th>
                <div class="row">
                    <div class="col-md-6">
                        Pizza name
                    </div>
                    <div class="col-md-2">
                        Quantity
                    </div>
                    <div class="col-md-4 text-center">
                        Total price
                    </div>
                </div>
            </th>
            <th>Status</th>
            <th>Manage</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach var="order" items="${orders}">
            <tr>
                <td>
                    <c:out value="${order.id}"/>
                </td>
                <td>
                    <fmt:formatDate value="${order.deliveryDate}" type="both"
                                    pattern="dd/MM/yyyy - HH:mm"/>
                </td>
                <td>
                    <c:forEach var="pizza" items="${order.selectedPizzas}">
                        <div class="row">
                            <div class="col-md-6">
                                <c:out value="${pizza.pizza.name}"/>
                            </div>
                            <div class="col-md-2 text-center">
                                <c:out value="${pizza.quantity}"/>
                            </div>
                            <div class="col-md-4 text-center">
                                <fmt:formatNumber type="number" minFractionDigits="2" maxFractionDigits="2"
                                                  value="${pizza.totalPrice}"/>&#8364;
                            </div>
                        </div>
                    </c:forEach>
                </td>
                <td>
                    <p class="block">Total:
                        <fmt:formatNumber type="number" minFractionDigits="2" maxFractionDigits="2"
                                          value="${order.totalPrice}"/>&#8364;
                    </p>

                    <p class="block">
                        <c:if test="${order.complete}">
                            Complete
                        </c:if>
                        <c:if test="${order.modifiable}">
                            Modifiable
                        </c:if>
                        <c:if test="${!order.modifiable}">
                            Unmodifiable
                        </c:if>
                    </p>
                    <c:if test="${user.isAdmin()}">
                        <p class="block">
                            Username: <c:out value="${order.user.username}"/>
                        </p>
                    </c:if>
                </td>
                <td>
                    <c:if test="${!order.complete}">
                        <a href="${pageContext.request.contextPath}/order/<c:out value="${order.id}"/>/complete"
                           class="btn btn-primary">Delivery is Complete</a>
                    </c:if>
                    <c:if test="${order.modifiable}">
                        <a href="${pageContext.request.contextPath}/order/<c:out value="${order.id}"/>/modify"
                           class="btn">Modify</a>

                        <form class="inline"
                              action="${pageContext.request.contextPath}/order/<c:out value="${order.id}"/>/delete"
                              method="POST">
                            <button class="btn btn-danger">Delete</button>
                        </form>
                    </c:if>
                    <c:if test="${user.isAdmin()}">
                        <c:if test="${order.modifiable}">
                            <a href="${pageContext.request.contextPath}/order/<c:out value="${order.id}"/>/unchangeable"
                               class="btn">Set Unchangeable</a>
                        </c:if>
                        <c:if test="${!order.modifiable}">
                            <a href="${pageContext.request.contextPath}/order/<c:out value="${order.id}"/>/changeable"
                               class="btn">Set Changeable</a>
                        </c:if>
                        <c:if test="${order.complete}">
                            <a href="${pageContext.request.contextPath}/order/<c:out value="${order.id}"/>/uncompleted"
                               class="btn">Set Uncompleted</a>
                        </c:if>
                    </c:if>
                </td>


            </tr>
        </c:forEach>
        </tbody>
    </table>
</t:main-layout>

src/main/webapp/WEB-INF/views/pizzaCreateForm.jsp
<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>

<t:main-layout>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form:form id="form" action="${pageContext.request.contextPath}/pizza/${actionType}" method="post"
                       modelAttribute="pizzaForm" class="form-horizontal" role="form">
                <s:bind path="*">
                    <c:if test="${status.error}">
                        <div id="message" class="alert alert-danger">
                            <c:forEach items="${status.errorMessages}" var="error">
                                <c:out value="${error}"/><br/>
                            </c:forEach>
                        </div>
                    </c:if>
                </s:bind>
                <legend>Create a pizza</legend>

                <div class="form-group error">
                    <form:label class="col-lg-2 control-label" path="name">
                        Name
                    </form:label>
                    <div class="col-lg-6">
                        <form:input path="name" class="form-control" placeholder="Choose a pizza name"
                                    required="required"/>
                        <s:bind path="name">
                            <c:if test="${status.error}">
                                <div class="alert alert-danger">
                                    <form:errors path="name" cssClass="error"/>
                                </div>
                            </c:if>
                        </s:bind>
                    </div>
                </div>
                <div class="form-group warning">
                    <form:label class="col-lg-2 control-label" path="ingredients">
                        Ingredients
                    </form:label>
                    <div class="col-lg-6">
                        <form:input class="form-control" path="ingredients" placeholder="Ingredients"/>
                        <s:bind path="ingredients">
                            <c:if test="${status.error}">
                                <div class="alert alert-danger">
                                    <form:errors path="ingredients" cssClass="error"/>
                                </div>
                            </c:if>
                        </s:bind>
                    </div>
                </div>
                <div class="form-group success">
                    <form:label class="col-lg-2 control-label" path="price">
                        Price
                    </form:label>
                    <div class="col-lg-6">
                        <form:input type="text" pattern="^\d*(\.\d{1,2}$)?" size="4" class="form-control" path="price"
                                    placeholder="Price" required="required"/>
                        <s:bind path="price">
                            <c:if test="${status.error}">
                                <div class="alert alert-danger">
                                    <form:errors path="price" cssClass="error"/>
                                </div>
                            </c:if>
                        </s:bind>
                    </div>
                </div>
                <p>
                    <button type="submit" class="btn btn-default">Submit</button>
                </p>
            </form:form>
        </div>
    </div>
</t:main-layout>

src/main/webapp/WEB-INF/views/pizzasList.jsp
<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>


<t:main-layout>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th>Name</th>
            <th>Ingredients</th>
            <th>Price</th>
            <th>Manage</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach var="pizza" items="${pizzas}">
            <tr>
                <td><c:out value="${pizza.name}"/></td>
                <td>
                    <c:out value="${pizza.ingredients}"/>

                </td>
                <td>
                    <fmt:formatNumber type="number" minFractionDigits="2" maxFractionDigits="2"
                                      value="${pizza.price}"/>

                </td>
                <td>
                    <a href="${pageContext.request.contextPath}/pizza/<c:out value="${pizza.id}"/>/edit"
                       class="btn btn-warning">Modify</a>

                    <form action="${pageContext.request.contextPath}/pizza/${pizza.id}/delete" method="post"
                          class="inline" role="form">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>


            </tr>
        </c:forEach>
        </tbody>
    </table>

</t:main-layout>